apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl (include "tsa.serviceAccountName" $) $ }}
{{ tpl (include "common.names.namespace" $) $ | indent 2 }}
  labels:
    {{- tpl (include "common.labels.labels" $) $ | nindent 4 }}
  annotations:
{{ tpl (toYaml .Values.server.serviceAccount.annotations) $ | indent 4 }}
