{{- if not .Values.createsecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- tpl (include "common.labels.labels" $) $ | nindent 4 }}
  name: {{ tpl (include "tsa.secret.name" $) $ }}
{{ tpl (include "common.names.namespace" $) $ | indent 2 }}
stringData:
  {{- if (eq .Values.server.secret.signer "tink")}}
  tink.keyset.enc: {{ required "Tink authentication token for Hashicorp Vault API is required" (tpl (toYaml .Values.server.secret.tink_enc_keyset) $) | indent 2  }}
  {{- end }}
  {{- if or (eq .Values.server.secret.signer "kms") (eq .Values.server.secret.signer "file") (eq .Values.server.secret.signer "tink") }}
  cert-chain: {{ required "PEM-encoded certificate chain is required" (tpl (toYaml .Values.server.secret.cert_chain) $) | indent 2 }}
  {{- end }}
  {{- if (eq .Values.server.secret.signer "file")}}
  signing-secret: {{ required "Signing secret required" (tpl (toYaml .Values.server.secret.signing_secret) $) | indent 2 }}
  signing-secret-password: {{ required "Password required for the signing secret" (tpl (.Values.server.secret.signing_secret_password) $) }}
  {{- end }}
  {{- if .Values.server.secret.creds }}
  cloud_credentials: {{ (tpl (toYaml .Values.server.secret.creds) $) | indent 2 }}
  {{- end }}
{{- end }}
