apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl (include "common.names.fullname" $) $ }}
{{ tpl (include "common.names.namespace" $) $ | indent 2 }}
  labels:
    {{- tpl (include "common.labels.labels" $) $ | nindent 4 }}
spec:
  replicas: {{ tpl (.Values.server.replicaCount | toString) $ }}
  selector:
    matchLabels:
      {{- tpl (include "common.labels.selectorLabels" $) $ | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ tpl (include (print $.Template.BasePath "/tsa-secret.yaml") $) $ | sha256sum }}
        {{- if .Values.server.podAnnotations }}
        {{- tpl (toYaml .Values.server.podAnnotations) $ | nindent 8 }}
        {{- end }}
      labels:
        {{- tpl (include "common.labels.selectorLabels" $) $ | nindent 8 }}
    spec:
      serviceAccountName: {{ tpl (include  "tsa.serviceAccountName" $) $ }}
      containers:
        - name: {{ tpl (include "common.names.fullname" $) $ }}
          image: "{{ tpl (include "common.images.image" .Values.server.image) $ }}"
          imagePullPolicy: "{{ tpl (.Values.server.image.imagePullPolicy) $ }}"
          {{- tpl (include "common.images.imagePullSecrets" (dict "pullSecrets" (list .Values.server.image.imagePullSecrets) "context" $)) $ | indent 10 }}
          args:
{{ tpl (include "tsa.server.args" $) $ | indent 12 }}
          {{- if or (.Values.server.extraEnvVars) (eq .Values.server.secret.signer "file") }}
          env:
          {{- end }}
{{- if eq .Values.server.secret.signer "file" }}
            - name: SIGNING_SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl (include "tsa.secret.name" $) $ }}
                  key: signing-secret-password
          {{- end }}
          {{- if .Values.server.extraEnvVars }}
{{ tpl (toYaml .Values.server.extraEnvVars) $ | indent 12 }}
          {{- end }}
          {{- if or .Values.server.extraEnvVarsCM .Values.server.extraEnvVarsSecret }}
          envFrom:
          {{- if .Values.server.extraEnvVarsCM }}
            - configMapRef:
               name: {{ tpl (.Values.server.extraEnvVarsCM) $ }}
          {{- end }}
          {{- if .Values.server.extraEnvVarsSecret }}
            - secretRef:
               name: {{ tpl (.Values.server.extraEnvVarsSecret) $ }}
          {{- end }}
          {{- end }}
          {{- if .Values.server.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.server.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.server.readinessProbe }}
          readinessProbe:
{{ tpl (toYaml .Values.server.readinessProbe) $ | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: tsa-secrets
              mountPath: "{{ .Values.server.secretMount }}"
              readOnly: true
          {{- if .Values.server.extraVolumeMounts }}
{{ tpl (toYaml .Values.server.extraVolumeMounts) $ | indent 12 }}
          {{- end }}
          ports:
{{- tpl (include "common.network.containerPorts" .Values.server.service.ports) $ | indent 12 }}
    {{- if .Values.server.resources }}
          resources:
{{ tpl (toYaml .Values.server.resources $) | indent 12 }}
    {{- end }}
    {{- if .Values.server.containerSecurityContext.enabled }}
          securityContext:
{{ tpl (omit .Values.server.containerSecurityContext "enabled" | toYaml) $ | indent 12 }}
    {{- end }}
    {{- if .Values.server.podSecurityContext.enabled }}
      securityContext:
{{ tpl (omit .Values.server.podSecurityContext "enabled" | toYaml) $ | indent 8 }}
    {{- end }}
    {{- if .Values.server.tolerations }}
      tolerations:
{{ tpl (toYaml .Values.server.tolerations) $ | indent 8 }}
    {{- end }}
    {{- if .Values.server.nodeSelector }}
      tolerations:
{{ tpl (toYaml .Values.server.nodeSelector) $ | indent 8 }}
    {{- end }}
      volumes:
        - name: tsa-secrets
          secret:
            secretName: {{ tpl (include "tsa.secret.name" $) $ }}
            items:
              - key: signing-secret
                path: signing-secret
              - key: cert-chain
                path: cert-chain
    {{- if .Values.server.extraVolumes }}
{{ tpl (toYaml .Values.server.extraVolumes) $ | indent 8 }}
    {{- end }}