apiVersion: v2
name: fulcio
description: |
  Fulcio is a free code signing Certificate Authority, built to make short-lived certificates available to anyone.

type: application

version: 3.0.0 # bumped for ctlog-v2
appVersion: 1.4.0

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: ctlog
    version: 0.3.0 # bumped for ctlog-v2
    repository: https://repo-securesign-helm-v2.apps.open-svc-sts.k1wl.p1.openshiftapps.com/helm-charts
    condition: ctlog.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: fulcio
      image: gcr.io/projectsigstore/fulcio@sha256:2d78059f645ab6e240b8ceba932308fe96fbfe84eeefc8622eedc8d15830f321
    - name: createcerts
      image: ghcr.io/sigstore/scaffolding/createcerts@sha256:73e7ac35d0e5169bd14a5cb6caed2e7d44277dec3d1de92e08f4d055523089a1
