apiVersion: v1
kind: Service
metadata:
  annotations:
{{- if .Values.server.service.annotations }}
{{ tpl (toYaml .Values.server.service.annotations $) . | indent 4 }}
{{- end }}
  labels:
    {{- tpl (include "common.labels.labels" $) $ | nindent 4 }}
{{- if .Values.server.service.labels }}
{{ tpl (toYaml .Values.server.service.labels) $ | indent 4 }}
{{- end }}
  name: {{ tpl (include "common.names.fullname" $) $ }}
{{ tpl (include "common.names.namespace" $) $ | indent 2 }}
spec:
  ports:
    {{- tpl (toYaml .Values.server.service.ports) $ | nindent 4 }}
  selector:
    {{- tpl (include "common.labels.selectorLabels" $) $ | nindent 4 }}
  type: "{{ tpl (.Values.server.service.type) $ }}"