apiVersion: v2
name: scaffold
description: Scaffolding the components of the sigstore architecture

type: application

version: 2.0.0
keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: fulcio
    version: 3.0.0 #bumped for ctlog-v2
    repository: https://repo-securesign-helm.apps.open-svc-sts.k1wl.p1.openshiftapps.com/helm-charts
    condition: fulcio.enabled
  - name: rekor
    version: 1.3.6
    repository: https://sigstore.github.io/helm-charts
    condition: rekor.enabled
  - name: trillian
    version: 0.2.8
    repository: https://sigstore.github.io/helm-charts
    condition: trillian.enabled
  - name: ctlog
    version: 0.3.0 #bumped for ctlog-v2
    repository: https://repo-securesign-helm.apps.open-svc-sts.k1wl.p1.openshiftapps.com/helm-charts
    condition: ctlog.enabled
  - name: tuf
    version: 0.1.4
    repository: https://sigstore.github.io/helm-charts
    condition: tuf.enabled
  - name: tsa
    version: 0.1.0
    repository: https://sigstore.github.io/helm-charts
    condition: tsa.enabled

annotations:
  artifacthub.io/license: Apache-2.0
